# Generated by Django 4.2.15 on 2024-10-21 15:13

from django.db import migrations, models
import django.utils.timezone
import redbox_app.redbox_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("redbox_core", "0024_user_ai_experience_user_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", redbox_app.redbox_core.models.SSOUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="invite_accepted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="invited_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_token_sent_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verified",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.EmailField(
                default="default@default.co.uk", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ai_experience",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="sso_user_set",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="fakepassword"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="sso_user_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]