# Generated by Django 5.1.2 on 2024-11-07 16:24

import redbox_app.redbox_core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0055_citation_source_citation_url_alter_citation_file"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", redbox_app.redbox_core.models.SSOUserManager()),
            ],
        ),
    ]
