# Generated by Django 5.1.5 on 2025-02-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0076_citation_text_in_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='new_route_retrieval_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
