# Generated by Django 5.1.5 on 2025-02-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0076_citation_text_in_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=254, unique=True, blank=True, null=True),
        ),
    ]
