# Generated by Django 5.1.5 on 2025-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0077_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
