# Generated by Django 5.1.5 on 2025-03-03 10:32

import redbox_app.redbox_core.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0078_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage, upload_to=redbox_app.redbox_core.models.build_s3_key),
        ),
    ]
