# Generated by Django 5.1.7 on 2025-04-16 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0080_alter_file_original_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSearchRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_text', models.TextField(max_length=32768)),
                ('user_text_rephrased', models.TextField(max_length=32768)),
                ('route', models.CharField(blank=True, max_length=25, null=True)),
                ('chunk_similarity_scores', models.TextField(max_length=32768)),
                ('ai_text', models.TextField(max_length=32768)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
