# Generated by Django 5.1.7 on 2025-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0081_monitorsearchroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uk_or_us_english",
            field=models.BooleanField(default=True),
        ),
    ]
