# Generated by Django 5.1.7 on 2025-04-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0081_monitorsearchroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorsearchroute',
            name='rag_cannot_answer',
        ),
    ]
