# Generated by Django 5.1.7 on 2025-06-04 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0083_citations_add_citation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agent_plans', models.TextField(max_length=32768)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redbox_core.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
