# Generated by Django 5.2.4 on 2025-09-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0085_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='url',
            field=models.URLField(blank=True, help_text='url for external', max_length=2048, null=True),
        ),
    ]
