# Generated by Django 5.1.7 on 2025-06-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0085_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="db_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="citation",
            name="table_names",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
