# Generated by Django 5.1.10 on 2025-07-24 11:52

import redbox_app.redbox_core.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0085_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="minio_path",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="original_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage,
                upload_to=redbox_app.redbox_core.models.build_s3_key,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("deleted", "Deleted"),
                    ("errored", "Errored"),
                    ("processing", "Processing"),
                ],
                default="processing",
            ),
        ),
    ]
