# Generated by Django 5.1.7 on 2025-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0086_citation_db_location_citation_table_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citation",
            name="db_location",
        ),
        migrations.RemoveField(
            model_name="citation",
            name="table_names",
        ),
        migrations.AddField(
            model_name="file",
            name="db_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="table_names",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
