# Generated by Django 5.2.4 on 2025-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0086_alter_citation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(blank=True, choices=[('Wikipedia', 'wikipedia'), ('UserUploadedDocument', 'user uploaded document'), ('GOV.UK', 'gov.uk'), ('WebSearch', 'Web Search')], default='UserUploadedDocument', help_text='source of citation', max_length=32, null=True),
        ),
    ]
