# Generated by Django 5.1.10 on 2025-10-07 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0087_alter_citation_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorWebSearchResults",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("user_text", models.TextField(max_length=32768)),
                ("web_search_urls", models.TextField(max_length=32768)),
                (
                    "chat_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="redbox_core.chatmessage",
                    ),
                ),
                (
                    "selected_files",
                    models.ManyToManyField(
                        null=True, related_name="+", to="redbox_core.file"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
