# Generated by Django 5.1.12 on 2025-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0087_alter_citation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessagetokenuse",
            name="model_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
