# Generated by Django 5.1.12 on 2025-10-17 11:44

from django.db import migrations
from django.db.migrations.state import StateApps
from django.conf import settings


def set_site(apps: StateApps, schema_editor):
    Site = apps.get_model("sites", "Site")
    domain = settings.ENVIRONMENT.hosts[0]

    Site.objects.update_or_create(
        id=1,
        defaults={"domain": domain, "name": domain}
    )



def revert_site(apps: StateApps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.filter(id=1).update(
        domain="example.com",
        name="example.com",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0090_team_fileteammembership_userteammembership'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(set_site, reverse_code=revert_site),
    ]
