# Generated by Django 5.1.10 on 2025-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0091_update_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorwebsearchresults",
            name="web_search_api_count",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="monitorwebsearchresults",
            name="selected_files",
            field=models.ManyToManyField(related_name="+", to="redbox_core.file"),
        ),
    ]
