# Generated by Django 5.1.12 on 2025-10-29 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0092_monitorwebsearchresults_web_search_api_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FileSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_skills",
                        to="redbox_core.file",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_skills",
                        to="redbox_core.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("file", "skill")},
            },
        ),
        migrations.CreateModel(
            name="BackendSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backend_skills",
                        to="redbox_core.chatllmbackend",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backend_skills",
                        to="redbox_core.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("backend", "skill")},
            },
        ),
        migrations.AddField(
            model_name="chatllmbackend",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="agent_backends",
                through="redbox_core.BackendSkill",
                to="redbox_core.skill",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages",
                to="redbox_core.skill",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="files",
                through="redbox_core.FileSkill",
                to="redbox_core.skill",
            ),
        ),
        migrations.CreateModel(
            name="TeamSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_skills",
                        to="redbox_core.skill",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="redbox_core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("team", "skill")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                through="redbox_core.TeamSkill",
                to="redbox_core.skill",
            ),
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="redbox_core.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="redbox_core.UserSkill",
                to="redbox_core.skill",
            ),
        ),
    ]
