# Generated by Django 5.2.7 on 2025-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0093_skill_agent_fileskill_agentskill_agent_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
