# Generated by Django 5.2.7 on 2025-11-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0094_agent_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
