# Generated by Django 5.2.8 on 2025-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0095_skill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileskill',
            name='file_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
