# Generated by Django 5.2.8 on 2025-11-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0096_fileskill_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='redbox_core.skill'),
        ),
    ]
