# Generated by Django 5.2.8 on 2025-11-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0097_chat_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for url routing and info page linking', max_length=100, unique=True),
        ),
    ]
