# Generated by Django 5.2.8 on 2025-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0099_alter_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(choices=[('Internal_Retrieval_Agent', 'Internal_Retrieval_Agent'), ('External_Retrieval_Agent', 'External_Retrieval_Agent'), ('Web_Search_Agent', 'Web_Search_Agent'), ('Legislation_Search_Agent', 'Legislation_Search_Agent'), ('Summarisation_Agent', 'Summarisation_Agent'), ('Tabular_Agent', 'Tabular_Agent'), ('Submission_Checker_Agent', 'Submission_Checker_Agent'), ('Submission_Question_Answer_Agent', 'Submission_Question_Answer_Agent')], max_length=100, unique=True),
        ),
    ]
