# Generated by Django 5.2.8 on 2025-12-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0100_alter_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='text_in_answer',
        ),
    ]
