# Generated by Django 5.2.8 on 2025-12-11 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0100_alter_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deselect_documents_on_load', models.BooleanField(default=False, help_text='Whether to reset selected documents when the chat is loaded')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_settings', to='redbox_core.skill')),
            ],
            options={
                'verbose_name_plural': 'Skill Settings',
                'ordering': ['created_at'],
            },
        ),
    ]
