# Generated by Django 5.2.9 on 2026-01-07
# Manually edited to preserve data when renaming Skill -> Tool

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("redbox_core", "0101_skillsettings"),
    ]

    operations = [
        # -------------------------------------------------
        # Rename ForeignKey fields: skill -> tool
        # -------------------------------------------------
        migrations.RenameField(
            model_name="userskill",
            old_name="skill",
            new_name="tool",
        ),
        migrations.RenameField(
            model_name="fileskill",
            old_name="skill",
            new_name="tool",
        ),
        migrations.RenameField(
            model_name="agentskill",
            old_name="skill",
            new_name="tool",
        ),
        migrations.RenameField(
            model_name="teamskill",
            old_name="skill",
            new_name="tool",
        ),
        migrations.RenameField(
            model_name="skillsettings",
            old_name="skill",
            new_name="tool",
        ),

        # -------------------------------------------------
        # Rename references on other models
        # -------------------------------------------------
        migrations.RenameField(
            model_name="chat",
            old_name="skill",
            new_name="tool",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="skill",
            new_name="tool",
        ),

        # -------------------------------------------------
        # Rename models
        # -------------------------------------------------
        migrations.RenameModel(old_name="Skill", new_name="Tool"),
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ["name"], "verbose_name_plural": "tools"},
        ),

        migrations.RenameModel(old_name="UserSkill", new_name="UserTool"),
        migrations.RenameModel(old_name="FileSkill", new_name="FileTool"),
        migrations.RenameModel(old_name="AgentSkill", new_name="AgentTool"),
        migrations.RenameModel(old_name="TeamSkill", new_name="TeamTool"),
        migrations.RenameModel(old_name="SkillSettings", new_name="ToolSettings"),

        # -------------------------------------------------
        # Rename database tables to match new model names
        # -------------------------------------------------
        migrations.AlterModelTable(name="tool", table="redbox_core_tool"),
        migrations.AlterModelTable(name="usertool", table="redbox_core_usertool"),
        migrations.AlterModelTable(name="filetool", table="redbox_core_filetool"),
        migrations.AlterModelTable(name="agenttool", table="redbox_core_agenttool"),
        migrations.AlterModelTable(name="teamtool", table="redbox_core_teamtool"),
        migrations.AlterModelTable(name="toolsettings", table="redbox_core_toolsettings"),
    ]
