# Generated by Django 5.2.9 on 2026-01-07 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0102_remove_agent_skills_alter_fileskill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsettings',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Toool Settings'},
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='skills',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='skills',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='skills',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='skills',
            new_name='tools',
        ),
        migrations.AlterField(
            model_name='agenttool',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='redbox_core.agent'),
        ),
        migrations.AlterField(
            model_name='agenttool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='redbox_core.tool'),
        ),
        migrations.AlterField(
            model_name='filetool',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tools', to='redbox_core.file'),
        ),
        migrations.AlterField(
            model_name='filetool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tools', to='redbox_core.tool'),
        ),
        migrations.AlterField(
            model_name='teamtool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tools', to='redbox_core.tool'),
        ),
        migrations.AlterField(
            model_name='toolsettings',
            name='tool',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_settings', to='redbox_core.tool'),
        ),
        migrations.AlterField(
            model_name='usertool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tools', to='redbox_core.tool'),
        ),
        migrations.AlterField(
            model_name='usertool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='agenttool',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filetool',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teamtool',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tool',
            table=None,
        ),
        migrations.AlterModelTable(
            name='toolsettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usertool',
            table=None,
        ),
    ]
