# Generated by Django 5.2.9 on 2026-01-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0103_alter_toolsettings_options_rename_skills_agent_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='security_classification',
            field=models.CharField(blank=True, choices=[('OFFICIAL', 'Official'), ('OFFICIAL_SENSITIVE', 'Official Sensitive'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default=''),
        ),
    ]
