# Generated by Django 5.2.9 on 2026-01-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0105_alter_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(choices=[('Planner_Agent', 'Planner_Agent'), ('Replanner_Agent', 'Replanner_Agent'), ('Internal_Retrieval_Agent', 'Internal_Retrieval_Agent'), ('External_Retrieval_Agent', 'External_Retrieval_Agent'), ('Web_Search_Agent', 'Web_Search_Agent'), ('Legislation_Search_Agent', 'Legislation_Search_Agent'), ('Summarisation_Agent', 'Summarisation_Agent'), ('Submission_Checker_Agent', 'Submission_Checker_Agent'), ('Submission_Question_Answer_Agent', 'Submission_Question_Answer_Agent'), ('Tabular_Agent', 'Tabular_Agent'), ('Knowledge_Base_Retrieval_Agent', 'Knowledge_Base_Retrieval_Agent')], max_length=100, unique=True),
        ),
    ]
