# Generated by Django 5.2.9 on 2026-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0106_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time_user',
            field=models.BooleanField(default=True),
        ),
    ]
