# Generated by Django 5.2.11 on 2026-03-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0109_alter_agent_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsettings',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Tool Settings'},
        ),
    ]
