# Generated by Django 5.2.11 on 2026-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0111_alter_user_ai_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the tool is accessible by all users'),
        ),
        migrations.AddField(
            model_name='usertool',
            name='access',
            field=models.CharField(choices=[('ALLOW', 'Allowed'), ('DENY', 'Denied')], default='ALLOW', max_length=20),
        ),
        migrations.AddField(
            model_name='usertool',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
