# Generated by Django 5.2.11 on 2026-05-02 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0112_customflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertool',
            options={'ordering': ['created_at'], 'verbose_name': 'User Tool', 'verbose_name_plural': 'User Tools'},
        ),
        migrations.AddField(
            model_name='tool',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the tool is accessible by all users'),
        ),
        migrations.AddField(
            model_name='usertool',
            name='access_type',
            field=models.CharField(choices=[('ALLOW', 'Allowed'), ('DENY', 'Denied')], default='ALLOW', max_length=20),
        ),
        migrations.AddField(
            model_name='usertool',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_user_id', models.EmailField(blank=True, max_length=254)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=48)),
                ('last_name', models.CharField(blank=True, max_length=48)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User SSO',
                'verbose_name_plural': 'User SSO',
            },
        ),
        migrations.CreateModel(
            name='ToolAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('DOMAIN', 'Domain')], max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('access_type', models.CharField(choices=[('ALLOW', 'Allowed'), ('DENY', 'Denied')], max_length=100)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='redbox_core.tool')),
            ],
            options={
                'verbose_name': 'Tool Access Rule',
                'verbose_name_plural': 'Tool Access Rules',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('tool', 'rule_type', 'value'), name='unique_tool_access_rule')],
            },
        ),
        migrations.CreateModel(
            name='UserSSOAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=2048)),
                ('attribute_type', models.CharField(choices=[('related_emails', 'Related Emails'), ('other', 'Other')], db_index=True, max_length=100)),
                ('sso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='redbox_core.usersso')),
            ],
            options={
                'indexes': [models.Index(fields=['attribute_type', 'value'], name='redbox_core_attribu_53c3d7_idx')],
                'unique_together': {('sso', 'value', 'attribute_type')},
            },
        ),
    ]
