# Generated by Django 5.2.11 on 2026-05-01 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0112_customflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the tool is accessible by all users'),
        ),
        migrations.AddField(
            model_name='usertool',
            name='access',
            field=models.CharField(choices=[('ALLOW', 'Allowed'), ('DENY', 'Denied')], default='ALLOW', max_length=20),
        ),
        migrations.AddField(
            model_name='usertool',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_user_id', models.EmailField(blank=True, max_length=254)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=48)),
                ('last_name', models.CharField(blank=True, max_length=48)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User SSO',
                'verbose_name_plural': 'User SSO',
            },
        ),
        migrations.CreateModel(
            name='UserSSOAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2048)),
                ('type', models.CharField(choices=[('related_emails', 'Related Emails'), ('other', 'Other')], db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='redbox_core.usersso')),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'value'], name='redbox_core_type_fb53a2_idx')],
                'unique_together': {('sso', 'value', 'type')},
            },
        ),
    ]
