# Generated by Django 5.2.12 on 2026-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0113_alter_usertool_options_tool_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_file_name',
            field=models.TextField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
