# Generated by Django 5.2.12 on 2026-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0113_alter_usertool_options_tool_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ingest_extraction_strategy_largest',
            field=models.CharField(choices=[('unstructured', 'Unstructured'), ('unstructured_auto', 'Unstructured Auto'), ('unstructured_fast', 'Unstructured Fast'), ('textract_document_analysis', 'Textract Document Analysis'), ('pymupdf', 'Pymupdf'), ('tabular', 'Tabular'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingest_extraction_strategy_normal',
            field=models.CharField(choices=[('unstructured', 'Unstructured'), ('unstructured_auto', 'Unstructured Auto'), ('unstructured_fast', 'Unstructured Fast'), ('textract_document_analysis', 'Textract Document Analysis'), ('pymupdf', 'Pymupdf'), ('tabular', 'Tabular'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
    ]
