# Generated by Django 5.2.12 on 2026-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0114_file_ingest_extraction_strategy_largest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ingest_chunking_strategy_largest',
            field=models.CharField(choices=[('overlapping_pages', 'Overlapping Pages'), ('page_by_page', 'Page By Page'), ('tabular', 'Tabular'), ('unstructured_chunk_by_title', 'Unstructured Chunk By Title'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingest_chunking_strategy_normal',
            field=models.CharField(choices=[('overlapping_pages', 'Overlapping Pages'), ('page_by_page', 'Page By Page'), ('tabular', 'Tabular'), ('unstructured_chunk_by_title', 'Unstructured Chunk By Title'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
    ]
