# Generated by Django 5.2.12 on 2026-06-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0114_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ingest_chunking_strategy_largest',
            field=models.CharField(choices=[('overlapping_pages', 'Overlapping Pages'), ('page_by_page', 'Page By Page'), ('tabular', 'Tabular'), ('unstructured_chunk_by_title', 'Unstructured Chunk By Title'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingest_chunking_strategy_normal',
            field=models.CharField(choices=[('overlapping_pages', 'Overlapping Pages'), ('page_by_page', 'Page By Page'), ('tabular', 'Tabular'), ('unstructured_chunk_by_title', 'Unstructured Chunk By Title'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingest_extraction_strategy_largest',
            field=models.CharField(choices=[('unstructured', 'Unstructured'), ('unstructured_auto', 'Unstructured Auto'), ('unstructured_fast', 'Unstructured Fast'), ('textract_document_analysis', 'Textract Document Analysis'), ('pymupdf', 'Pymupdf'), ('tabular', 'Tabular'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingest_extraction_strategy_normal',
            field=models.CharField(choices=[('unstructured', 'Unstructured'), ('unstructured_auto', 'Unstructured Auto'), ('unstructured_fast', 'Unstructured Fast'), ('textract_document_analysis', 'Textract Document Analysis'), ('pymupdf', 'Pymupdf'), ('tabular', 'Tabular'), ('unspecified', 'Unspecified')], default='unspecified', max_length=64, null=True),
        ),
    ]
