# Generated by Django 5.2.12 on 2026-07-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0118_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
