# Generated by Django 5.2.12 on 2026-07-27 13:33

from django.db import migrations, models


ICON_SLUGS = {
    "submissions-checker": "icons/submission-checker-icon.svg",
    "invest-lens": "icons/invest-lens-icon.svg",
}


def set_icon_slugs(apps, schema_editor):
    Tool = apps.get_model("redbox_core", "Tool")
    for slug, icon_slug in ICON_SLUGS.items():
        Tool.objects.filter(slug=slug).update(icon_slug=icon_slug)


def reverse(apps, schema_editor):
    Tool = apps.get_model("redbox_core", "Tool")
    Tool.objects.filter(slug__in=ICON_SLUGS).update(icon_slug="")


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0119_file_ingested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='icon_slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(set_icon_slugs, reverse),
    ]
