# Generated by Django 5.2.12 on 2026-07-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0119_file_ingested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(blank=True, choices=[('Wikipedia', 'wikipedia'), ('UserUploadedDocument', 'user uploaded document'), ('GOV.UK', 'gov.uk'), ('WebSearch', 'Web Search'), ('Unverified', 'Unverified')], default='UserUploadedDocument', help_text='source of citation', max_length=32, null=True),
        ),
    ]
