# Generated by Django 5.2.12 on 2026-07-23 10:29

from django.db import migrations, models


def set_null_sources_to_unverified(apps, schema_editor):
    Citation = apps.get_model("redbox_core", "Citation")
    Citation.objects.filter(source__isnull=True).update(source="Unverified")


def set_unverified_sources_to_null(apps, schema_editor):
    Citation = apps.get_model("redbox_core", "Citation")
    Citation.objects.filter(source="Unverified").update(source=None)


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0119_file_ingested_at'),
    ]

    operations = [
        # 1. First, make the field nullable in the schema (if rolling back, this runs last)
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(
                choices=[
                    ('Wikipedia', 'wikipedia'),
                    ('UserUploadedDocument', 'user uploaded document'),
                    ('GOV.UK', 'gov.uk'),
                    ('WebSearch', 'Web Search'),
                    ('Unverified', 'Unverified'),
                ],
                default='UserUploadedDocument',
                help_text='source of citation',
                max_length=32,
                null=True,
                blank=True,
            ),
        ),

        # 2. Run Python data fix
        migrations.RunPython(
            set_null_sources_to_unverified,
            reverse_code=set_unverified_sources_to_null,
        ),

        # 3. Finally, enforce null=False in the schema (if rolling back, this runs first)
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(
                choices=[
                    ('Wikipedia', 'wikipedia'),
                    ('UserUploadedDocument', 'user uploaded document'),
                    ('GOV.UK', 'gov.uk'),
                    ('WebSearch', 'Web Search'),
                    ('Unverified', 'Unverified'),
                ],
                default='UserUploadedDocument',
                help_text='source of citation',
                max_length=32,
                null=False,
                blank=False,
            ),
        ),
    ]
