# Generated by Django 5.2.12 on 2026-07-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0120_tool_icon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[('Wikipedia', 'wikipedia'), ('UserUploadedDocument', 'user uploaded document'), ('GOV.UK', 'gov.uk'), ('WebSearch', 'Web Search'), ('Unverified', 'Unverified')], default='UserUploadedDocument', help_text='source of citation', max_length=32),
        ),
    ]
