# Generated by Django 5.2.12 on 2026-07-31 10:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox_core', '0121_alter_citation_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_positive', models.BooleanField()),
                ('reason', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('INACCURATE', 'It was inaccurate'), ('UNASKED', "It wasn't what I asked for"), ('LACKED_DETAIL', 'It was lacking detail'), ('CONFUSING', 'I found it confusing'), ('OTHER', 'Other')], max_length=32), blank=True, default=list, size=None)),
                ('detail', models.TextField(blank=True, default='')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='redbox_core.chatmessage')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('is_positive', False), ('reason', []), _connector='OR'), name='reason_only_when_negative'), models.CheckConstraint(condition=models.Q(('is_positive', False), ('detail', ''), _connector='OR'), name='detail_only_when_negative')],
            },
        ),
    ]
