ENABLE_DICTATION = "enable_dictation"
ENABLE_TEAMS = "enable_teams"
ENABLE_TOOLS = "enable_tools"
ENABLE_MODEL_SELECTOR = "enable_model_selector"
ENABLE_ACTIVITY_EVENTS = "enable_activity_events"
ENABLE_ASSIST_REBRAND = "enable_assist_rebrand"
ENABLE_FIRST_TIME_USER = "enable_first_time_user"
DISABLE_ENVIRONMENT_BANNER = "disable_environment_banner"
