from datetime import UTC, date, datetime

from data_classes import (
    AccountManagementObjective,
    CompanyDetails,
    CompanyInteraction,
    CompanyShort,
    InvestmentProject,
)

# Company 1
STATIC_COMPANY_ID = "cmp_001"

STATIC_COMPANY_SHORT = CompanyShort(
    id=STATIC_COMPANY_ID,
    address_1="1 Test Street",
    address_2=None,
    address_postcode="SW1A 1AA",
    address_country="UK",
    company_number="12345678",
    description="Static test company",
    name="Acme Industries Ltd",
    turnover_gbp=1_500_000,
)

STATIC_COMPANY_DETAILS = CompanyDetails(
    id=STATIC_COMPANY_ID,
    name="Acme Industries Ltd",
    description="Static test company for MCP testing",
    address_1="1 Test Street",
    address_2=None,
    address_county="Greater London",
    address_postcode="SW1A 1AA",
    address_country="UK",
    address_area_name="Westminster",
    address_town="London",
    company_number="12345678",
    turnover_gbp=1_500_000,
    business_type="Manufacturing",
    duns_number="123456789",
    export_experience="Experienced",
    global_ultimate_duns_number="987654321",
    headquarter_type="UK HQ",
    is_number_of_employees_estimated=False,
    is_turnover_estimated=False,
    number_of_employees=120,
    registered_address_1="1 Test Street",
    registered_address_2=None,
    registered_address_country="UK",
    registered_address_county="Greater London",
    registered_address_postcode="SW1A 1AA",
    registered_address_area_name="Westminster",
    registered_address_town="London",
    sector="Advanced Manufacturing",
    export_segment="Industrial",
    export_sub_segment="Machinery",
    trading_names=["Acme"],
    turnover="£1.5m",
    turnover_usd=1_900_000,
    uk_region="London",
    vat_number="GB123456789",
    website="https://example.com",
    is_out_of_business=False,
    strategy="Expand EU exports",
)

STATIC_INTERACTION = CompanyInteraction(
    team_region="Europe",
    team_country="UK",
    interaction_year=2025,
    interaction_financial_year="2024/25",
    company_name="Acme Industries Ltd",
    company_sector="Advanced Manufacturing",
    date_of_interaction=date(2025, 1, 15),
    interaction_subject="Quarterly export review",
    interaction_theme_investment_or_export="Export",
)

STATIC_OBJECTIVE = AccountManagementObjective(
    id="amo_001",
    subject="Increase EU exports",
    detail="Support company with EU distributor introductions",
    target_date=date(2025, 6, 30),
    has_blocker=False,
    blocker_description=None,
    progress=40,
    created_on=datetime(2024, 11, 1, tzinfo=UTC),
    modified_on=datetime(2025, 1, 10, tzinfo=UTC),
    created_by_id="user_001",
    modified_by_id="user_002",
    company_id=STATIC_COMPANY_ID,
)

STATIC_INVESTMENT_PROJECT = InvestmentProject(
    id="ip_001",
    name="UK Expansion Project",
    description="New manufacturing facility",
    sector="Advanced Manufacturing",
    stage="Active",
    status="In progress",
    investment_type="FDI",
    investor_type="Foreign",
    investor_company_id=STATIC_COMPANY_ID,
    investor_company_sector="Manufacturing",
    uk_company_id=STATIC_COMPANY_ID,
    total_investment=25_000_000,
    number_new_jobs=80,
    number_safeguarded_jobs=20,
    likelihood_to_land="High",
    created_on=datetime(2024, 10, 1, tzinfo=UTC),
    modified_on=datetime(2025, 1, 5, tzinfo=UTC),
    actual_land_date=None,
    estimated_land_date=date(2025, 9, 30),
    address_1="Industrial Park",
    address_2=None,
    address_town="Birmingham",
    address_county="West Midlands",
    address_country="UK",
    address_postcode="B1 1AA",
    actual_uk_regions=None,
    anonymous_description=None,
    associated_non_fdi_r_and_d_project_id=None,
    average_salary="£45,000",
    business_activities=["Manufacturing", "R&D"],
    client_relationship_manager_id="crm_001",
    client_requirements=None,
    client_contact_ids=["contact_001"],
    client_contact_names=["Jane Doe"],
    client_contact_emails=["jane.doe@example.com"],
    competing_countries=["Germany", "Poland"],
    country_investment_originates_from="USA",
    created_by_id="user_001",
    delivery_partners=["Local Authority"],
    export_revenue=True,
    first_active_on=datetime(2024, 10, 5, tzinfo=UTC),
    fdi_type="Expansion",
    fdi_value="High",
    foreign_equity_investment=60,
    government_assistance=True,
    gross_value_added=5_000_000,
    gva_multiplier=1.4,
    level_of_involvement="High",
    modified_by_id="user_002",
    new_tech_to_uk=True,
    non_fdi_r_and_d_budget=False,
    other_business_activity=None,
    project_arrived_in_triage_on=datetime(2024, 9, 15, tzinfo=UTC),
    project_assurance_adviser_id="paa_001",
    project_moved_to_won=None,
    project_manager_id="pm_001",
    project_reference="IP-2025-001",
    proposal_deadline=date(2025, 3, 31),
    r_and_d_budget=True,
    referral_source_activity="Trade show",
    referral_source_activity_marketing=None,
    referral_source_activity_website=None,
    specific_programme=["Levelling Up"],
    strategic_drivers=["Market access", "Cost efficiency"],
    team_member_ids=["tm_001", "tm_002"],
    uk_company_sector="Manufacturing",
    possible_uk_regions=["West Midlands"],
    eyb_lead_ids=None,
)

# Company 2
STATIC_COMPANY_ID_2 = "cmp_002"

STATIC_COMPANY_SHORT_2 = CompanyShort(
    id=STATIC_COMPANY_ID_2,
    address_1="99 Innovation Way",
    address_2="Unit 5",
    address_postcode="M1 2AB",
    address_country="UK",
    company_number="87654321",
    description="Second test company",
    name="Acme Solutions Ltd",
    turnover_gbp=2_200_000,
)

STATIC_COMPANY_DETAILS_2 = CompanyDetails(
    id=STATIC_COMPANY_ID_2,
    name="Acme Solutions Ltd",
    description="Static test company for MCP testing",
    address_1="99 Innovation Way",
    address_2="Unit 5",
    address_county="Greater Manchester",
    address_postcode="M1 2AB",
    address_country="UK",
    address_area_name="Manchester City Centre",
    address_town="Manchester",
    company_number="87654321",
    turnover_gbp=2_200_000,
    business_type="Technology",
    duns_number="987654321",
    export_experience="Limited",
    global_ultimate_duns_number="123456789",
    headquarter_type="UK HQ",
    is_number_of_employees_estimated=False,
    is_turnover_estimated=False,
    number_of_employees=85,
    registered_address_1="99 Innovation Way",
    registered_address_2="Unit 5",
    registered_address_country="UK",
    registered_address_county="Greater Manchester",
    registered_address_postcode="M1 2AB",
    registered_address_area_name="Manchester City Centre",
    registered_address_town="Manchester",
    sector="Software & IT",
    export_segment="Tech Services",
    export_sub_segment="Software Solutions",
    trading_names=["BetaTech"],
    turnover="£2.2m",
    turnover_usd=2_800_000,
    uk_region="North West",
    vat_number="GB876543210",
    website="https://betatech.example.com",
    is_out_of_business=False,
    strategy="Expand SaaS offerings to EU",
)

STATIC_INTERACTION_2 = CompanyInteraction(
    team_region="Europe",
    team_country="UK",
    interaction_year=2025,
    interaction_financial_year="2024/25",
    company_name="Acme Solutions Ltd",
    company_sector="Software & IT",
    date_of_interaction=date(2025, 2, 20),
    interaction_subject="Product expansion discussion",
    interaction_theme_investment_or_export="Export",
)

STATIC_OBJECTIVE_2 = AccountManagementObjective(
    id="amo_002",
    subject="Increase EU SaaS clients",
    detail="Support company with EU client introductions and marketing",
    target_date=date(2025, 8, 31),
    has_blocker=False,
    blocker_description=None,
    progress=25,
    created_on=datetime(2024, 12, 1, tzinfo=UTC),
    modified_on=datetime(2025, 1, 12, tzinfo=UTC),
    created_by_id="user_003",
    modified_by_id="user_004",
    company_id=STATIC_COMPANY_ID_2,
)

STATIC_INVESTMENT_PROJECT_2 = InvestmentProject(
    id="ip_002",
    name="Tech Hub Development",
    description="New software development hub",
    sector="Software & IT",
    stage="Active",
    status="In progress",
    investment_type="FDI",
    investor_type="Domestic",
    investor_company_id=STATIC_COMPANY_ID_2,
    investor_company_sector="Technology",
    uk_company_id=STATIC_COMPANY_ID_2,
    total_investment=10_000_000,
    number_new_jobs=50,
    number_safeguarded_jobs=10,
    likelihood_to_land="Medium",
    created_on=datetime(2024, 11, 1, tzinfo=UTC),
    modified_on=datetime(2025, 1, 8, tzinfo=UTC),
    actual_land_date=None,
    estimated_land_date=date(2025, 12, 31),
    address_1="Tech Park",
    address_2=None,
    address_town="Manchester",
    address_county="Greater Manchester",
    address_country="UK",
    address_postcode="M2 3CD",
    actual_uk_regions=None,
    anonymous_description=None,
    associated_non_fdi_r_and_d_project_id=None,
    average_salary="£50,000",
    business_activities=["Software Development", "Cloud Services"],
    client_relationship_manager_id="crm_002",
    client_requirements=None,
    client_contact_ids=["contact_002"],
    client_contact_names=["John Smith"],
    client_contact_emails=["john.smith@example.com"],
    competing_countries=["Ireland", "Netherlands"],
    country_investment_originates_from="UK",
    created_by_id="user_003",
    delivery_partners=["Local Enterprise Partnership"],
    export_revenue=True,
    first_active_on=datetime(2024, 11, 5, tzinfo=UTC),
    fdi_type="Expansion",
    fdi_value="Medium",
    foreign_equity_investment=40,
    government_assistance=True,
    gross_value_added=3_000_000,
    gva_multiplier=1.3,
    level_of_involvement="Medium",
    modified_by_id="user_004",
    new_tech_to_uk=True,
    non_fdi_r_and_d_budget=True,
    other_business_activity=None,
    project_arrived_in_triage_on=datetime(2024, 10, 15, tzinfo=UTC),
    project_assurance_adviser_id="paa_002",
    project_moved_to_won=None,
    project_manager_id="pm_002",
    project_reference="IP-2025-002",
    proposal_deadline=date(2025, 4, 30),
    r_and_d_budget=True,
    referral_source_activity="Industry Conference",
    referral_source_activity_marketing=None,
    referral_source_activity_website=None,
    specific_programme=["Tech Growth Fund"],
    strategic_drivers=["Innovation", "Market access"],
    team_member_ids=["tm_003", "tm_004"],
    uk_company_sector="Software & IT",
    possible_uk_regions=["North West"],
    eyb_lead_ids=None,
)
